# site settings
title: Fatemeh Jamshidian
subtitle: Networks, Paint, and Questions!
email: youremailaddress@gmail.com
description: A corner for brain networks, <br /> images that speak and <br />thoughts wander between science and art. 
baseurl: "" # the subpath of your site, e.g. /blog
url:"https://fatemehjamshidian.github.io" # the base hostname & protocol for your site
author:


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
